version: "3"

services:
  postgres:
    image: "postgres:9.5"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3333:3000"
    volumes:
      - .:/umanniApi
      - gems:/gems
    env_file:
      - '.env'
    stdin_open: true
    tty: true
 
volumes:
  postgres:
  gems:
